fr = {
    "article_files": "Fiche article",
    "article_pdf": "Article PDF",
    "presentation_pdf": "Présentation PDF disponible prochainement",
    "authors": "Auteurs",
    "affiliations": "Affiliations",
    "theme": "Thématique",
    "session": "Session",
    "abstract": "Résumé",
    "list_contributions": "Liste des contributions",
    "list_authors": "Liste des auteurs",
    "conference_proceedings": "Actes de la conférence",
    "mise": "mise en forme web : ",
    "ficheI": "Fiches d'évaluation des sessions",
    "documents": "Documents à distribuer aux chairmen de chaque session, pour l'évaluation des sessions et des présentations.",
    "pour": "Pour chaque session il y a à remplir :",
    "a_session_evaluation_sheet": "une fiche d'évaluation de la session",
    "the_presentation_evaluation_sheets": "des fiches d'évaluation des présentation (une par contribution)",
    "ensemble": "1) Ensemble des fiches",
    "fichesIV": "Fiches concaténées dans un fichiers, classées par session :",
    "telecharge": "Télécharger les",
    "pdf": "fiches PDF",
    "voir": "Voir les",
    "html": "fiches HTML",
    "number_of_session_files": 'Nombre de fiches "session"',
    "number_of_article_files": 'Nombre de fiches "article"',
    "separees": "2) Fiches séparées par sessions",
    "clique": "Cliquer sur une session pour télécharger la fiche PDF correspondante",
    "president": "Président(e)",
    "eval": "Évaluation des présentations",
    "contributions": "Évaluation des contributions complètes dans l'optique de leur présélection pour publication dans des revues partenaires.",
    "session_chair": "Président(es) de session",
    "verify_your_name": "Entourez votre nom (et amendez/corrigez si nécessaire).",
    "titre": "Titre",
    "presentee": "Présentée par :",
    "presentation_article": "Votre évaluation de l'article et de la présentation",
    "contribution": "Contenu scientifique de la contribution complète :",
    "faible": "faible",
    "average": "moyenne",
    "good": "bonne",
    "excellent": "excellente",
    "original": "Originalité des travaux présentés :",
    "qualite": "Qualité de la présentation orale ou poster :",
    "echanges": "Qualité des échanges :",
    "note": "Note globale de la contribution :",
    "publication": "Publication dans une revue partenaire",
    "concernant": "Concernant la présélection par le CS SGE de la contribution pour publication dans une revue internationale partenaire, êtes vous :",
    "défavorable": "défavorable",
    "plutôt_def": "plutôt défavorable",
    "plutôt_fav": "plutôt favorable",
    "favorable": "favorable",
    "nb": "NB : Si le papier est présélectionné, il sera procédé à un reviewing conforme aux règles des revues partenaires (EJEE, EPE, EJAP). Ce reviewing sera réalisé par un comité ad-hoc sur la base de la version complète en langue anglaise de l’article SGE.",
    "optional_comments": "Commentaires éventuels :",
    "session_summary": "Compte-rendu de session",
    "chair_documents": "Documents pour les Chairmen",
    "chair_documents_description": "Documents à distribuer aux chairmen de chaque session, pour l'évaluation des sessions et des présentations.",
    "fill_out_for_each_session": "Pour chaque session il y a à remplir :",
    "files_classified_by_session": "(fiches classées par session)",
    "number_of_presentations_carried_out": "Nombre de présentations réalisées :",
    "your_session_evaluation": "Votre évaluation de la session",
    "approximate_number_attendees": "Nombre approximatif de présents :",
    "global_presentation_quality": "Qualité globale des présentations :",
    "interaction_discussion_quality": "Qualité des échanges et discussions :",
    "session_duration": "La durée de la session est-elle :",
    "too_short": "trop courte",
    "appropriate": "appropriée",
    "too_long": "trop longue",
    "physical_conditions": "Les conditions matérielles sont elles :",
    "poor": "mauvaises",
    "comite": "Le comité d’organisation SGE vous remercie vivement pour votre contribution et votre expertise, essentielles au symposium.",
    "article": "article",
    "list_all_contributions": "Liste de toutes les contributions",
    "session_program": "Programme des sessions",
    "the_authors": "Les auteurs",
    "website": "Site internet de la conférence :",
    "sponsors": "Sponsors",
    "labs_list": "Liste des laboratoire",
    "labs": "Laboratoires et centres de recherche",
    "list_of_contributions": "Liste des contributions, classées par laboratoires, centres de recherche ou institutions des contributeurs de la conférence :",
    "program": "Programme",
    "program_detail": "Programme détaillé",
    "room": "Salle",
    "index": "Index des auteurs",
    "references": "auteurs référencés",
    "session_title": "Session",
    "lsession": "session",
    "articles": "articles dans cette session :",
    "return": "Retour à la liste des sessions",
    "topic": "Topic"
}